services:
  - docker

before_install:
  - docker build -t adi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run adi/react-test -e CI='true' npm run test

after_success:
  - docker build -t adi/multi-client ./client
  - docker build -t adi/multi-nginx ./nginx
  - docker build -t adi/multi-server ./server
  - docker build -t adi/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push adi/multi-client
  - docker push adi/multi-nginx
  - docker push adi/multi-server
  - docker push adi/multi-worker
