services:
  - docker

before_install:
  - docker build -t adi/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run adi/react-test -e CI='true' npm run test

after_success:
  - docker build -t adi/multi-client ./client
  - docker build -t adi/multi-nginx ./nginx
  - docker build -t adi/multi-server ./server
  - docker build -t adi/multi-worker ./worker
